name: Git ref

on:
  workflow_dispatch: {}

jobs:
  ref-from-gh:
    name: Git ref
    runs-on: ubuntu-20.04
    steps:
      - name: Print Git ref
        run: |
          echo "github.ref: ${{ github.ref }}"
          echo "GITHUB_REF: ${{ GITHUB_REF }}"
          echo "GITHUB_REF_NAME: ${{ GITHUB_REF_NAME }}"
  version-from-git-ref:
    name: Set version from Git ref
    runs-on: ubuntu-20.04
    steps:
      - name: Set version
        run: |
          if [[ ${GITHUB_REF_NAME/\//-} =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-.+)?$ ]]; then
          echo "VERSION=${GITHUB_REF_NAME/\//-}" >> $GITHUB_ENV
          else
          echo "VERSION=${{ github.sha }}" >> $GITHUB_ENV
          fi
      - name: Print version
        run: |
          echo "Version: ${VERSION}"
